<a href="https://colab.research.google.com/github/AshmitaChowdhury92/Machine_Learning_Journey/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np


In [9]:
########### 0D Array/Scalar ##############
a = np.array(4)
print(a)
a.ndim

4


0

In [10]:
####### 1D Array/ Vector ##########

a = np.array([1,2,3])
print (a)
a.ndim


[1 2 3]


1

In [11]:
####### 2D Array ##########

a = np.array( [     [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]       ] )

print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [12]:
####### 3D Array ##########



a = np.array( [     [[1, 2, 3], [2, 2, 2]],
                    [[4, 5, 6], [1, 1, 1]],
                    [[7, 8, 9], [3, 3, 3]]       ] )

print(a)
print(a.ndim)
a.shape



[[[1 2 3]
  [2 2 2]]

 [[4 5 6]
  [1 1 1]]

 [[7 8 9]
  [3 3 3]]]
3


(3, 2, 3)

In [14]:
####### 3D Array ##########



a = np.array( [     [[1, 2, 3], [2, 2, 2],[10,20,30],[40,50,60]],
                    [[4, 5, 6], [1, 1, 1],[10,20,30],[40,50,60]],
                    [[7, 8, 9], [3, 3, 3],[10,20,30],[40,50,60]]       ] )

print(a)
print(a.ndim)
a.shape

[[[ 1  2  3]
  [ 2  2  2]
  [10 20 30]
  [40 50 60]]

 [[ 4  5  6]
  [ 1  1  1]
  [10 20 30]
  [40 50 60]]

 [[ 7  8  9]
  [ 3  3  3]
  [10 20 30]
  [40 50 60]]]
3


(3, 4, 3)